import test from 'node:test';
import assert from 'node:assert/strict';
import { buildForecastFactorAttributionStatus } from '../src/forecast-factor-attribution.js';
import { createLiveShadowForecastRecords } from '../src/forecast-outcome-ledger.js';

const LEVELS=[-.9,-.6,-.3,.1,.4,.8];
function rec(i,o={}){const value=o.value??LEVELS[i%LEVELS.length],positive=o.invert?value<0:value>0,at=new Date(Date.UTC(2026,0,1+i)).toISOString();return{forecastId:`attr:${o.vectorVersion||'fv-v1'}:${i}`,validationMode:'LIVE_SHADOW_OOS',factorFeatureVectorPolicyVersion:o.noSnapshotVersion?null:o.vectorVersion||'fv-v1',factorScorePolicyVersion:'score-v1',assetClass:'EQUITY',horizon:'month1',forecastAt:at,forecastSampleDate:at.slice(0,10),factorDomainSnapshot:o.noSnapshot?[]:[{domain:'MOMENTUM',value,weight:.16,verifiedDriverCount:1},{domain:'QUALITY',value:value*.8,weight:.12,verifiedDriverCount:1}],status:o.open?'OPEN':'MATURED',positiveOutcome:o.open?null:positive?1:0,realisedOutcome:o.open?null:{realisedReturnPct:o.invert?-value*8:value*8}};}

test('new record persists compact factor-domain snapshot',()=>{const at='2026-08-12T20:00:00.000Z',shadow={policyVersion:'shadow-v2',generatedAt:at,companyId:'company:ABC',instrumentId:'company:ABC',displayName:'ABC',symbol:'ABC',assetClass:'EQUITY',mode:'SHADOW_ONLY',decisionImpact:'NONE',historicalPatternForecast:{policyVersion:'pattern-v2',asOf:at,currentPattern:{regime:'BULL'},horizons:{month1:{tradingDays:21,rawProbabilityPositive:.6,expectedReturnPct:3}}},forecast:{horizons:{month1:{probabilityPositive:null,evidenceQualityScore:80}}},multiFactorResearch:{horizons:{month1:{factorScore:{policyVersion:'score-v1',status:'LATENT_SCORE_READY',latentScore:.4,rawLatentScore:.4},featureVector:{policyVersion:'fv-v1',availableDomainCount:2,availableWeight:.28,features:[{domain:'MOMENTUM',available:true,value:.6,weight:.16,verifiedDriverCount:1,evidenceIds:['not-for-ledger']},{domain:'QUALITY',available:true,value:.3,weight:.12,verifiedDriverCount:2},{domain:'GROWTH',available:false,value:null,weight:.1,verifiedDriverCount:0}]}}}}};const[r]=createLiveShadowForecastRecords([shadow],[{companyId:'company:ABC',listing:{symbol:'ABC',mic:'XNAS',currency:'USD'},referencePrice:{value:100,timestamp:at,currency:'USD',source:'test'}}]);assert.equal(r.factorFeatureVectorPolicyVersion,'fv-v1');assert.deepEqual(r.factorDomainSnapshot.map(x=>x.domain),['MOMENTUM','QUALITY']);assert.equal(JSON.stringify(r.factorDomainSnapshot).includes('not-for-ledger'),false);});
test('pre-snapshot records do not enter attribution lineage',()=>{const s=buildForecastFactorAttributionStatus({records:Array.from({length:150},(_,i)=>rec(i,{noSnapshotVersion:true}))});assert.equal(s.lineageRecordCount,0);});
test('feature-vector versions are never pooled',()=>{const s=buildForecastFactorAttributionStatus({records:[...Array.from({length:80},(_,i)=>rec(i,{vectorVersion:'fv-v1'})),...Array.from({length:80},(_,i)=>rec(i+80,{vectorVersion:'fv-v2'}))]});assert.equal(s.groupCount,2);});
test('strong domain ordering is supported',()=>{const m=buildForecastFactorAttributionStatus({records:Array.from({length:180},(_,i)=>rec(i))}).groups[0].domains.find(d=>d.domain==='MOMENTUM');assert.equal(m.status,'PREDICTIVE_DIRECTION_SUPPORTED');assert.ok(m.rocAuc>.95);assert.equal(m.automaticWeightAdjustmentEnabled,false);});
test('inverted domain is surfaced without auto reweight',()=>{const s=buildForecastFactorAttributionStatus({records:Array.from({length:220},(_,i)=>rec(i,{invert:true}))});const m=s.groups[0].domains.find(d=>d.domain==='MOMENTUM');assert.equal(m.status,'INVERTED_OR_NONPREDICTIVE');assert.equal(m.manualWeightReviewCandidate,true);assert.equal(s.automaticWeightAdjustmentEnabled,false);});
test('OPEN snapshots add coverage but cannot leak outcomes',()=>{const s=buildForecastFactorAttributionStatus({records:[...Array.from({length:90},(_,i)=>rec(i)),...Array.from({length:100},(_,i)=>rec(i+90,{open:true}))]});const m=s.groups[0].domains.find(d=>d.domain==='MOMENTUM');assert.equal(m.lineageCoverageCount,190);assert.equal(m.maturedSampleSize,90);assert.equal(m.status,'INSUFFICIENT_OOS_HISTORY');assert.equal(s.forecastMayInfluenceFinalAction,false);});
